<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Data collection | The R News Book</title>
  <meta name="description" content="This is a summary of experience and methods developped for the analysis of news flow." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Data collection | The R News Book" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a summary of experience and methods developped for the analysis of news flow." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data collection | The R News Book" />
  
  <meta name="twitter:description" content="This is a summary of experience and methods developped for the analysis of news flow." />
  

<meta name="author" content="Claude Grasland, Romain Leconte, Hugues Pecout, Etienne Toureille, …" />


<meta name="date" content="2020-07-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="data-check.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">My Book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Objectives</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="data-collect.html"><a href="data-collect.html"><i class="fa fa-check"></i><b>3</b> Data collection</a><ul>
<li class="chapter" data-level="3.1" data-path="data-collect.html"><a href="data-collect.html#data-level-1-title-of-news"><i class="fa fa-check"></i><b>3.1</b> DATA LEVEL 1 : Title of news</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-collect.html"><a href="data-collect.html#download-titles-with-mediacloud-interface"><i class="fa fa-check"></i><b>3.1.1</b> Download titles with mediacloud interface</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-collect.html"><a href="data-collect.html#transformation-and-storage-in-quanteda-format."><i class="fa fa-check"></i><b>3.1.2</b> Transformation and storage in quanteda format.</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-collect.html"><a href="data-collect.html#data-level-2-title-of-news-description"><i class="fa fa-check"></i><b>3.2</b> DATA LEVEL 2 : Title of news + description</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-collect.html"><a href="data-collect.html#metadata"><i class="fa fa-check"></i><b>3.2.1</b> metadata</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-collect.html"><a href="data-collect.html#load-.csv-file"><i class="fa fa-check"></i><b>3.2.2</b> Load .csv file</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-collect.html"><a href="data-collect.html#cleaning-the-html-code-in-description-file"><i class="fa fa-check"></i><b>3.2.3</b> Cleaning the html code in description file</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-collect.html"><a href="data-collect.html#transformation-of-textdescription-in-quanteda-corpus"><i class="fa fa-check"></i><b>3.2.4</b> Transformation of text+description in quanteda corpus</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-collect.html"><a href="data-collect.html#data-level-3-full-text"><i class="fa fa-check"></i><b>3.3</b> DATA LEVEL 3 : Full text</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-check.html"><a href="data-check.html"><i class="fa fa-check"></i><b>4</b> Data Check and Clean</a><ul>
<li class="chapter" data-level="4.1" data-path="data-check.html"><a href="data-check.html#prerequites-quanteda-or-tidytext"><i class="fa fa-check"></i><b>4.1</b> Prerequites : quanteda (or tidytext)</a></li>
<li class="chapter" data-level="4.2" data-path="data-check.html"><a href="data-check.html#check-1-length-of-texts"><i class="fa fa-check"></i><b>4.2</b> CHECK 1 : length of texts</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data-check.html"><a href="data-check.html#number-of-sentences"><i class="fa fa-check"></i><b>4.2.1</b> Number of sentences</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-check.html"><a href="data-check.html#number-of-tokens"><i class="fa fa-check"></i><b>4.2.2</b> Number of tokens</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-check.html"><a href="data-check.html#check-2-time-distribution"><i class="fa fa-check"></i><b>4.3</b> CHECK 2 : Time distribution</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data-check.html"><a href="data-check.html#news-without-date"><i class="fa fa-check"></i><b>4.3.1</b> News without date</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-check.html"><a href="data-check.html#distribution-of-news-through-time"><i class="fa fa-check"></i><b>4.3.2</b> Distribution of news through time</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-check.html"><a href="data-check.html#check-3-suspect-words"><i class="fa fa-check"></i><b>4.4</b> CHECK 3 : Suspect words</a><ul>
<li class="chapter" data-level="4.4.1" data-path="data-check.html"><a href="data-check.html#tips-1-simple-word-fequencies"><i class="fa fa-check"></i><b>4.4.1</b> Tips 1 : simple word fequencies</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-check.html"><a href="data-check.html#tips-2-most-frequent-n-grams"><i class="fa fa-check"></i><b>4.4.2</b> Tips 2 : most frequent n-grams</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="data-check.html"><a href="data-check.html#check-4-human-expertise"><i class="fa fa-check"></i><b>4.5</b> CHECK 4 : Human expertise</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/ClaudeGrasland/newsbook" target="blank"></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The R News Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data_collect" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Data collection</h1>
<p>We can have different use of data, depending on the amount of text available. Basically, we will distingush between three cases corresponding to three levels of information :</p>
<ul>
<li><strong>title of news</strong> : typically, the case of data downloaded on mediacloud</li>
<li><strong>title of news</strong> + description : typically the case of data obtained by webscrapping of RSS flows and parsing of the XML code.</li>
<li>**full text of *news** : typically the data obtained through a private provider of newspapers (Factiva, EuroPresse, LexisNexis …) of by (non legal) scrapping of text through the URL’s.</li>
</ul>
<div id="data-level-1-title-of-news" class="section level2">
<h2><span class="header-section-number">3.1</span> DATA LEVEL 1 : Title of news</h2>
<div id="download-titles-with-mediacloud-interface" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Download titles with mediacloud interface</h3>
<p>We suppose that you want to analyze the title of the news collected by the New York Times during the first semester of 2020. You can easily proceed to such a collection with the application Mediacloud.</p>
<p><a href="https://explorer.mediacloud.org" class="uri">https://explorer.mediacloud.org</a></p>
<p>You need firstly to register (for free) in order to create an account. Then you can select your media, select your period and select all stories by using the request ’*’ as in the example presented below.</p>
<p><img src="pics/mc001.png" /><!-- --></p>
<p>Below your request, you obtain a graphic entitled <em>Attention Over Time</em> with the distribution of the number of news published per day which help you to verify if the distribution of news is regular through time. In our example, you an notice a classical week cycle (with decrease of the number of news publish during the week-end). But you can also observe a discontinuity at the beginning of May 2020 with a decline to a lower level of production of news.</p>
<p><img src="pics/mc002.png" /><!-- -->
Going down, you will find a news panel entitled <em>Total Attention</em> which gives you the total number of stories found. In our example, we have a total of 47522 stories produced by the NYT during the first semester of 2020.</p>
<p><img src="pics/mc003.png" /><!-- --></p>
<p>Finally, by clicking on the button <em>Download all story URLS</em>, you can get a .csv file that you can easily load in your favorite porgramming language. In the case of R, you can load it with a program like this.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="data-collect.html#cb1-1"></a>df&lt;-<span class="kw">read.csv</span>(<span class="dt">file =</span> <span class="st">&quot;_data/mc/en_USA_nytime_20200101_20200630.csv&quot;</span>,</span>
<span id="cb1-2"><a href="data-collect.html#cb1-2"></a>             <span class="dt">sep=</span><span class="st">&quot;,&quot;</span>,</span>
<span id="cb1-3"><a href="data-collect.html#cb1-3"></a>             <span class="dt">header=</span>T,</span>
<span id="cb1-4"><a href="data-collect.html#cb1-4"></a>             <span class="dt">encoding =</span> <span class="st">&quot;UTF-8&quot;</span>,</span>
<span id="cb1-5"><a href="data-collect.html#cb1-5"></a>             <span class="dt">stringsAsFactors =</span> F)</span>
<span id="cb1-6"><a href="data-collect.html#cb1-6"></a><span class="kw">str</span>(df)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:	30265 obs. of  10 variables:
##  $ stories_id   : int  1483747633 1483747632 1483779604 1483817555 1483817553 1483858519 1483858517 1483858514 1483858512 1483858499 ...
##  $ publish_date : chr  &quot;2020-01-01 00:00:08&quot; &quot;2020-01-01 00:05:07&quot; &quot;2020-01-01 01:00:05&quot; &quot;2020-01-01 03:00:11&quot; ...
##  $ title        : chr  &quot;Meteor Showers in 2020 That Will Light Up Night Skies&quot; &quot;Rocket Launches, Trips to Mars and More 2020 Space and Astronomy Events&quot; &quot;What’s on TV Wednesday: A Linda Ronstadt Doc and ‘Doctor Who’&quot; &quot;Why Did the U.S. Become the Focus of Iraqis’ Anger?&quot; ...
##  $ url          : chr  &quot;https://www.nytimes.com/2020/01/01/science/meteor-showers-2020.html&quot; &quot;https://www.nytimes.com/2020/01/01/science/space-astronomy-2020.html&quot; &quot;https://www.nytimes.com/2020/01/01/arts/television/whats-on-tv-wednesday-a-linda-ronstadt-doc-and-doctor-who.html&quot; &quot;https://www.nytimes.com/2020/01/01/world/middleeast/iraq-embassy-iran.html&quot; ...
##  $ language     : chr  &quot;en&quot; &quot;en&quot; &quot;en&quot; &quot;en&quot; ...
##  $ ap_syndicated: chr  &quot;False&quot; &quot;False&quot; &quot;False&quot; &quot;False&quot; ...
##  $ themes       : chr  &quot;&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...
##  $ media_id     : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ media_name   : chr  &quot;New York Times&quot; &quot;New York Times&quot; &quot;New York Times&quot; &quot;New York Times&quot; ...
##  $ media_url    : chr  &quot;http://nytimes.com&quot; &quot;http://nytimes.com&quot; &quot;http://nytimes.com&quot; &quot;http://nytimes.com&quot; ...</code></pre>
<p><strong>N.B.</strong> We can notice, without being able to explain this fact, that the number of stories downloaded (30265), which is less than what was announced by the mediacloud interface (47522). May be it is related to the elimination of duplicates ?</p>
</div>
<div id="transformation-and-storage-in-quanteda-format." class="section level3">
<h3><span class="header-section-number">3.1.2</span> Transformation and storage in quanteda format.</h3>
<p>Currently, the size of the file (unzipped) is equal to 7.3 Mb. But we can observe that a lot of information are the same for all news and should not necessarily be kept. We can also exclude the url field if we are not interested in. We propose therefore to use a better form of storage based on <code>quanteda</code> format.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="data-collect.html#cb3-1"></a><span class="co"># Create Quanteda corpus</span></span>
<span id="cb3-2"><a href="data-collect.html#cb3-2"></a>qd&lt;-<span class="kw">corpus</span>(df<span class="op">$</span>title)</span>
<span id="cb3-3"><a href="data-collect.html#cb3-3"></a></span>
<span id="cb3-4"><a href="data-collect.html#cb3-4"></a><span class="co"># Add date</span></span>
<span id="cb3-5"><a href="data-collect.html#cb3-5"></a>qd<span class="op">$</span>date&lt;-df<span class="op">$</span>publish_date</span>
<span id="cb3-6"><a href="data-collect.html#cb3-6"></a></span>
<span id="cb3-7"><a href="data-collect.html#cb3-7"></a><span class="co"># Add initial meta</span></span>
<span id="cb3-8"><a href="data-collect.html#cb3-8"></a><span class="kw">meta</span>(qd,<span class="st">&quot;language&quot;</span>)&lt;-df<span class="op">$</span>language[<span class="dv">1</span>]</span>
<span id="cb3-9"><a href="data-collect.html#cb3-9"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_id&quot;</span>)&lt;-df<span class="op">$</span>media_id[<span class="dv">1</span>]</span>
<span id="cb3-10"><a href="data-collect.html#cb3-10"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_name&quot;</span>)&lt;-df<span class="op">$</span>media_name[<span class="dv">1</span>]</span>
<span id="cb3-11"><a href="data-collect.html#cb3-11"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_url&quot;</span>)&lt;-df<span class="op">$</span>media_url[<span class="dv">1</span>]</span>
<span id="cb3-12"><a href="data-collect.html#cb3-12"></a></span>
<span id="cb3-13"><a href="data-collect.html#cb3-13"></a><span class="co"># Add supplementary meta</span></span>
<span id="cb3-14"><a href="data-collect.html#cb3-14"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_country&quot;</span>)&lt;-<span class="st">&quot;USA&quot;</span></span>
<span id="cb3-15"><a href="data-collect.html#cb3-15"></a><span class="kw">meta</span>(qd,<span class="st">&quot;data_source&quot;</span>)&lt;-<span class="st">&quot;Media Cloud &quot;</span></span>
<span id="cb3-16"><a href="data-collect.html#cb3-16"></a><span class="kw">meta</span>(qd,<span class="st">&quot;data_time&quot;</span>)&lt;-<span class="st">&quot;Download the 2020-07-06&quot;</span></span>
<span id="cb3-17"><a href="data-collect.html#cb3-17"></a><span class="kw">meta</span>(qd,<span class="st">&quot;data_author&quot;</span>)&lt;-<span class="st">&quot;Elaborated by Claude Grasland&quot;</span></span></code></pre></div>
<p>We have created a quanteda object with a lot of information stored in various fields. The structure of the object is the following one</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="data-collect.html#cb4-1"></a><span class="kw">str</span>(qd)</span></code></pre></div>
<pre><code>##  &#39;corpus&#39; Named chr [1:30265] &quot;Meteor Showers in 2020 That Will Light Up Night Skies&quot; ...
##  - attr(*, &quot;names&quot;)= chr [1:30265] &quot;text1&quot; &quot;text2&quot; &quot;text3&quot; &quot;text4&quot; ...
##  - attr(*, &quot;docvars&quot;)=&#39;data.frame&#39;:	30265 obs. of  4 variables:
##   ..$ docname_: chr [1:30265] &quot;text1&quot; &quot;text2&quot; &quot;text3&quot; &quot;text4&quot; ...
##   ..$ docid_  : Factor w/ 30265 levels &quot;text1&quot;,&quot;text2&quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##   ..$ segid_  : int [1:30265] 1 1 1 1 1 1 1 1 1 1 ...
##   ..$ date    : chr [1:30265] &quot;2020-01-01 00:00:08&quot; &quot;2020-01-01 00:05:07&quot; &quot;2020-01-01 01:00:05&quot; &quot;2020-01-01 03:00:11&quot; ...
##  - attr(*, &quot;meta&quot;)=List of 3
##   ..$ system:List of 5
##   .. ..$ package-version:Classes &#39;package_version&#39;, &#39;numeric_version&#39;  hidden list of 1
##   .. .. ..$ : int [1:3] 2 1 0
##   .. ..$ r-version      :Classes &#39;R_system_version&#39;, &#39;package_version&#39;, &#39;numeric_version&#39;  hidden list of 1
##   .. .. ..$ : int [1:3] 4 0 2
##   .. ..$ system         : Named chr [1:3] &quot;Windows&quot; &quot;x86-64&quot; &quot;CIST&quot;
##   .. .. ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;sysname&quot; &quot;machine&quot; &quot;user&quot;
##   .. ..$ directory      : chr &quot;C:/claude/git/newsbook&quot;
##   .. ..$ created        : Date[1:1], format: &quot;2020-07-08&quot;
##   ..$ object:List of 2
##   .. ..$ unit   : chr &quot;documents&quot;
##   .. ..$ summary:List of 2
##   .. .. ..$ hash: chr(0) 
##   .. .. ..$ data: NULL
##   ..$ user  :List of 8
##   .. ..$ language     : chr &quot;en&quot;
##   .. ..$ media_id     : int 1
##   .. ..$ media_name   : chr &quot;New York Times&quot;
##   .. ..$ media_url    : chr &quot;http://nytimes.com&quot;
##   .. ..$ media_country: chr &quot;USA&quot;
##   .. ..$ data_source  : chr &quot;Media Cloud &quot;
##   .. ..$ data_time    : chr &quot;Download the 2020-07-06&quot;
##   .. ..$ data_author  : chr &quot;Elaborated by Claude Grasland&quot;</code></pre>
<p>We can look at the first titles with <em>head()</em></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="data-collect.html#cb6-1"></a><span class="kw">kable</span>(<span class="kw">head</span>(qd,<span class="dv">3</span>))</span></code></pre></div>
<table>
<colgroup>
<col width="7%" />
<col width="92%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">text1</td>
<td align="left">Meteor Showers in 2020 That Will Light Up Night Skies</td>
</tr>
<tr class="even">
<td align="left">text2</td>
<td align="left">Rocket Launches, Trips to Mars and More 2020 Space and Astronomy Events</td>
</tr>
<tr class="odd">
<td align="left">text3</td>
<td align="left">What’s on TV Wednesday: A Linda Ronstadt Doc and ‘Doctor Who’</td>
</tr>
</tbody>
</table>
<p>We can get meta information on each stories with <em>summary()</em></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="data-collect.html#cb7-1"></a><span class="kw">summary</span>(qd,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Corpus consisting of 30265 documents, showing 3 documents:
## 
##   Text Types Tokens Sentences                date
##  text1    10     10         1 2020-01-01 00:00:08
##  text2    12     13         1 2020-01-01 00:05:07
##  text3    13     14         1 2020-01-01 01:00:05</code></pre>
<p>We can get meta information about the full document</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="data-collect.html#cb9-1"></a><span class="kw">meta</span>(qd)</span></code></pre></div>
<pre><code>## $language
## [1] &quot;en&quot;
## 
## $media_id
## [1] 1
## 
## $media_name
## [1] &quot;New York Times&quot;
## 
## $media_url
## [1] &quot;http://nytimes.com&quot;
## 
## $media_country
## [1] &quot;USA&quot;
## 
## $data_source
## [1] &quot;Media Cloud &quot;
## 
## $data_time
## [1] &quot;Download the 2020-07-06&quot;
## 
## $data_author
## [1] &quot;Elaborated by Claude Grasland&quot;</code></pre>
<p>We can finally save the object in RDS format</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="data-collect.html#cb11-1"></a><span class="kw">saveRDS</span>(qd,<span class="st">&quot;_data/qd/en_USA_nytime_20200101_20200630.RDS&quot;</span>)</span></code></pre></div>
<p>We have kept all the information present in the initial file, but also added specific metadata of interest for us. The size of the storage is now equal to 1.2Mb which means a division by 6 as compared to the initial .csv file downloaded from Media Cloud.</p>
</div>
</div>
<div id="data-level-2-title-of-news-description" class="section level2">
<h2><span class="header-section-number">3.2</span> DATA LEVEL 2 : Title of news + description</h2>
<div id="metadata" class="section level3">
<h3><span class="header-section-number">3.2.1</span> metadata</h3>
<p>First, we define a distant directory where news are stored and we look at the metadata file :</p>
<pre><code>## [1] &quot;mc2019_meta.csv&quot; &quot;qd&quot;              &quot;raw&quot;</code></pre>
<pre><code>##   media_id                                     url                      name
## 1    39962          http://www.24ora.com/index.php                  24ora-aw
## 2    38880 http://www.khaleejtimes.com/index00.asp              khaleejtimes
## 3    40717             http://www.lanacion.com.ar/               lanacion-AR
## 4    38931                http://www.armenews.com/                  armenews
## 5    39594              http://www.panorama.am/ru/            panorama-am-ru
## 6    19320                   http://www.smh.com.au The Sydney Morning Herald
##   pub_country pub_state language     media_type stories_per_day first_story
## 1         ABW                 es digital_native           23,98  2013-03-18
## 2         ARE     AE-DU       en   print_native           34,14  2013-03-11
## 3         ARG      AR-C       es   print_native           84,94  2013-05-27
## 4         ARM                 fr   print_native            34,1  2013-03-11
## 5         ARM                 ru digital_native            34,6  2013-03-11
## 6         AUS    AU-NSW       en   print_native          206,09  2014-02-24</code></pre>
<p>If we are specifically interested in a country e.g. France) we can check which sources are available for this specific ountry by using its ISO3 code (e.g. FRA)</p>
<pre><code>##     media_id                                    url                    name
## 110    39120                http://www.lefigaro.fr/                lefigaro
## 111    41322             http://www.ouest-france.fr             OuestFrance
## 112    39909             http://www.laprovence.com/              laprovence
## 113    40602             http://www.lest-eclair.fr/             lest-eclair
## 114    41611               http://www.la-croix.com/                la-croix
## 115    40894                  http://www.lunion.fr/                 L&#39;union
## 116    39802            http://www.lavoixdunord.fr/            lavoixdunord
## 117    42084             http://www.ledauphine.com/              ledauphine
## 118    41553               http://www.ladepeche.fr/               ladepeche
## 119    41565       http://www.larep.fr/accueil.html                   larep
## 120    41352          http://www.estrepublicain.fr/          estrepublicain
## 121    39055     http://www.republicain-lorrain.fr/     republicain-lorrain
## 122    41401    http://www.lanouvellerepublique.fr/    lanouvellerepublique
## 123    40342               http://www.leprogres.fr/               leprogres
## 124    40931              http://www.nicematin.com/               nicematin
## 125    39072                 http://www.lemonde.fr/                Le Monde
## 126    39201                     http://www.dna.fr/              dna-france
## 127    39263                 http://www.lalsace.fr/              lalsace-de
## 128    42068               http://www.varmatin.com/                varmatin
## 129    41583                 http://www.lepoint.fr/                 LePoint
## 130    40303 http://www.lepopulaire.fr/accueil.html             lepopulaire
## 131    39309             http://www.corsematin.com/              corsematin
## 132    41372                http://www.sudouest.fr/               Sud Ouest
## 133    41138               http://www.midilibre.fr/               midilibre
## 134    40105            http://www.lindependant.fr/            lindependant
## 135    39645 http://www.larepubliquedespyrenees.fr/ larepubliquedespyrenees
## 136    39973        http://www.courrierdelouest.fr/        courrierdelouest
## 137    40476                http://www.lesechos.fr/                LesEchos
## 138    41936           http://www.charentelibre.fr/           charentelibre</code></pre>
</div>
<div id="load-.csv-file" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Load .csv file</h3>
<p>If we are interesting in the regional newspaper <em>Sud-Ouest</em>, we pick the media_id number (41372) in order to load the corresponding file in the raw directory :</p>
<pre><code>## &#39;data.frame&#39;:	81653 obs. of  8 variables:
##  $ stories_id  : int  113642735 105929893 105014675 106119376 114086884 114034480 114338347 114611476 113400389 113372136 ...
##  $ title       : chr  &quot;Lot-et-Garonne : un homme tape ses parents parce qu&#39;ils veulent vendre la maison&quot; &quot;\&quot;Thierry\&quot;, l&#39;ancien chef présumé d&#39;ETA est mort à l&#39;hôpital&quot; &quot;Chaque année les pilules contraceptives provoquent 20 décès et  2500 \&quot;accidents\&quot;&quot; &quot;Jean-Pierre Elissalde a pris des amphétamines durant sa carrière&quot; ...
##  $ url         : chr  &quot;http://www.sudouest.fr/2013/05/03/cocumont-47-un-homme-tape-ses-parents-parce-qu-ils-veulent-vendre-la-maison-1&quot;| __truncated__ &quot;http://www.sudouest.fr/2013/03/30/thierry-l-ancien-chef-presume-d-eta-est-mort-a-l-hopital-1010669-754.php#xtor=RSS-10521769&quot; &quot;http://www.sudouest.fr/2013/03/26/chaque-annee-les-pilules-contraceptives-provoquent-20-deces-et-2500-accidents&quot;| __truncated__ &quot;http://www.sudouest.fr/2013/03/31/jean-pierre-elissalde-a-pris-des-amphetamines-durant-sa-carriere-1010963-773.&quot;| __truncated__ ...
##  $ publish_date: chr  &quot;2013-05-03 09:00:16&quot; &quot;2013-03-30 16:32:02&quot; &quot;2013-03-26 09:55:46&quot; &quot;2013-03-31 15:00:05&quot; ...
##  $ media_id    : int  41372 41372 41372 41372 41372 41372 41372 41372 41372 41372 ...
##  $ media_name  : chr  &quot;Sud Ouest&quot; &quot;Sud Ouest&quot; &quot;Sud Ouest&quot; &quot;Sud Ouest&quot; ...
##  $ media_url   : chr  &quot;http://www.sudouest.fr/&quot; &quot;http://www.sudouest.fr/&quot; &quot;http://www.sudouest.fr/&quot; &quot;http://www.sudouest.fr/&quot; ...
##  $ description : chr  &quot;&lt;p&gt;&lt;img src=\&quot;http://www.sudouest.fr/images/2013/05/03/1043114_gendarmerie-1000_165x110.jpg\&quot; align=\&quot;left\&quot; hs&quot;| __truncated__ &quot;&lt;p&gt;&lt;img src=\&quot;http://www.sudouest.fr/images/2013/03/30/l-arrestation-tres-mediatisee-de-thierry-le-21-mai-2008-&quot;| __truncated__ &quot;&lt;p&gt;&lt;img src=\&quot;http://www.sudouest.fr/images/2013/03/26/le-rapport-preconise-diverses-pratiques-afin-de-limiter-&quot;| __truncated__ &quot;&lt;p&gt;&lt;img src=\&quot;http://www.sudouest.fr/images/2013/03/31/jean-pierre-elissalde_1134167_165x110.JPG\&quot; align=\&quot;left&quot;| __truncated__ ...</code></pre>
<p>We can recognize many variables from our first example of download of title from Mediacloud. But with a new field called description that add more or less text, depending of the media under investigation.</p>
</div>
<div id="cleaning-the-html-code-in-description-file" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Cleaning the html code in description file</h3>
<p>We have generally a high risk to find html codes in the description field which are not of prior interest for textual analysis. The problem is clearly present in our example :</p>
<pre><code>## [1] &quot;&lt;p&gt;&lt;img src=\&quot;http://www.sudouest.fr/images/2013/05/03/1043114_gendarmerie-1000_165x110.jpg\&quot; align=\&quot;left\&quot; hspace=\&quot;10\&quot; /&gt;Les parents d&#39;un homme de 48 ans voulaient vendre la maison familiale. Mal leur en a pris.&lt;br&gt;Un couple habitant Cocumont projetaient de vendre leur maison familiale mais leur fils n&#39;a visiblement pas apprécié cette décision. A tel point que l&#39;homme, âgé de 48 ans, s&#39;en est pris à ses géniteurs le 30 avril dernier. Au volant de... &lt;a href=\&quot;http://www.sudouest.fr/2013/05/03/cocumont-47-un-homme-tape-ses-parents-parce-qu-ils-veulent-vendre-la-maison-1043114-3666.php#xtor=RSS-10521769\&quot;&gt;Lire la suite&lt;/a&gt;&lt;/p&gt;&quot;               
## [2] &quot;&lt;p&gt;&lt;img src=\&quot;http://www.sudouest.fr/images/2013/03/30/l-arrestation-tres-mediatisee-de-thierry-le-21-mai-2008-a_1133578_165x110.JPG\&quot; align=\&quot;left\&quot; hspace=\&quot;10\&quot; /&gt;Javier Lopez Peña, dit \&quot;Thierry\&quot; est décédé des suites d&#39;un AVC à l&#39;âge de 54 ans. Il avait été interpellé à Bordeaux en 2008.&lt;br&gt;Javier Lopez Peña, dit \&quot;Thierry\&quot;, 54 ans, ancien chef présumé de l&#39;ETA interpellé en 2008 à Bordeaux, est mort dans la nuit de vendredi à samedi à l&#39;hôpital parisien de la Pitié-Salpêtrière... &lt;a href=\&quot;http://www.sudouest.fr/2013/03/30/thierry-l-ancien-chef-presume-d-eta-est-mort-a-l-hopital-1010669-754.php#xtor=RSS-10521769\&quot;&gt;Lire la suite&lt;/a&gt;&lt;/p&gt;&quot;</code></pre>
<pre><code>## [1] &quot;&lt;p&gt;\n                    &lt;img src=\&quot;https://images.sudouest.fr/30/12/2019/5e098c2566a4bd266879ab54/idevice_01_mirror/australie-recrudescence-des-incendies-des-milliers-de-touristes-pourraient-etre-pris-au-piege.jpg\&quot; align=\&quot;left\&quot; hspace=\&quot;10\&quot;/&gt;                    Des centaines de feux de forêts brûlent actuellement à travers le continent, notamment dans la région très touristique d&#39;East Gippsland où des milliers de vacanciers pourraient être pris au piège en raison d&#39;une nouvelle vague de chaleur.&lt;br&gt;                    Des milliers de touristes pourraient se retrouver lundi pris au piège dans le... &lt;a href=\&quot;https://www.sudouest.fr/2019/12/30/australie-recrudescence-des-incendies-des-milliers-de-touristes-pourraient-etre-pris-au-piege-7007857-4803.php\&quot;&gt;Lire la suite&lt;/a&gt;&lt;/p&gt;&quot;          
## [2] &quot;&lt;p&gt;\n                    &lt;img src=\&quot;https://images.sudouest.fr/30/12/2019/5e09eaec66a4bdf45179ab64/idevice_01_mirror/population-5-956-978-habitants-la-nouvelle-aquitaine-est-la-4e-region-la-plus-peuplee-de-france.jpg\&quot; align=\&quot;left\&quot; hspace=\&quot;10\&quot;/&gt;                    Selon les derniers chiffres du recensement, 66 524 000 habitants vivent en France au 1er janvier 2017 dont 5 956 978 en Nouvelle-Aquitaine. Une région qui reste attractive et qui doit surtout sa hausse de population aux migrations résidentielles. .&lt;br&gt;                    Au 1er janvier 2017, selon les chiffres publiés ce lundi 30 décembre par... &lt;a href=\&quot;https://www.sudouest.fr/2019/12/30/population-5-956-978-habitants-la-nouvelle-aquitaine-est-la-4e-region-la-plus-peuplee-de-france-7008263-10407.php\&quot;&gt;Lire la suite&lt;/a&gt;&lt;/p&gt;&quot;</code></pre>
<p>Therefore, we can proceed to an immediate cleaning through a function. One of the most simple one is proposed below, but can be further completed for specific situation</p>
<pre><code>## [1] &quot;Les parents d&#39;un homme de 48 ans voulaient vendre la maison familiale. Mal leur en a pris.Un couple habitant Cocumont projetaient de vendre leur maison familiale mais leur fils n&#39;a visiblement pas apprécié cette décision. A tel point que l&#39;homme, âgé de 48 ans, s&#39;en est pris à ses géniteurs le 30 avril dernier. Au volant de... Lire la suite&quot;
## [2] &quot;Javier Lopez Peña, dit \&quot;Thierry\&quot; est décédé des suites d&#39;un AVC à l&#39;âge de 54 ans. Il avait été interpellé à Bordeaux en 2008.Javier Lopez Peña, dit \&quot;Thierry\&quot;, 54 ans, ancien chef présumé de l&#39;ETA interpellé en 2008 à Bordeaux, est mort dans la nuit de vendredi à samedi à l&#39;hôpital parisien de la Pitié-Salpêtrière... Lire la suite&quot;</code></pre>
<pre><code>## [1] &quot;\n                                        Des centaines de feux de forêts brûlent actuellement à travers le continent, notamment dans la région très touristique d&#39;East Gippsland où des milliers de vacanciers pourraient être pris au piège en raison d&#39;une nouvelle vague de chaleur.                    Des milliers de touristes pourraient se retrouver lundi pris au piège dans le... Lire la suite&quot;     
## [2] &quot;\n                                        Selon les derniers chiffres du recensement, 66 524 000 habitants vivent en France au 1er janvier 2017 dont 5 956 978 en Nouvelle-Aquitaine. Une région qui reste attractive et qui doit surtout sa hausse de population aux migrations résidentielles. .                    Au 1er janvier 2017, selon les chiffres publiés ce lundi 30 décembre par... Lire la suite&quot;</code></pre>
<p>In our example, we can see that the description is based on a numbr of characters rather than on a number of sentences, which produce a cut followed by <em>Lire la suite</em>. It can therefore be relevant to eliminate immediately the final part But the cleaning procedure is generally much longer and complex, especially when the corpus cover many years. Indeed, the style of description may have change through time. This point will be discuss in more details in the next chapter.</p>
</div>
<div id="transformation-of-textdescription-in-quanteda-corpus" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Transformation of text+description in quanteda corpus</h3>
<p>As we have done previously, we will store the resul in a quanteda corpus object with associated metadata. But before to do that we have to merge title + description in a same text where title will be the first sentence.</p>
<p>N.B. I am not quite sure of the good separator to be used between title and description</p>
<pre><code>## [1] &quot;Lot-et-Garonne : un homme tape ses parents parce qu&#39;ils veulent vendre la maison.\n.Les parents d&#39;un homme de 48 ans voulaient vendre la maison familiale. Mal leur en a pris.Un couple habitant Cocumont projetaient de vendre leur maison familiale mais leur fils n&#39;a visiblement pas apprécié cette décision. A tel point que l&#39;homme, âgé de 48 ans, s&#39;en est pris à ses géniteurs le 30 avril dernier. Au volant de... Lire la suite&quot;
## [2] &quot;\&quot;Thierry\&quot;, l&#39;ancien chef présumé d&#39;ETA est mort à l&#39;hôpital.\n.Javier Lopez Peña, dit \&quot;Thierry\&quot; est décédé des suites d&#39;un AVC à l&#39;âge de 54 ans. Il avait été interpellé à Bordeaux en 2008.Javier Lopez Peña, dit \&quot;Thierry\&quot;, 54 ans, ancien chef présumé de l&#39;ETA interpellé en 2008 à Bordeaux, est mort dans la nuit de vendredi à samedi à l&#39;hôpital parisien de la Pitié-Salpêtrière... Lire la suite&quot;</code></pre>
<pre><code>## [1] &quot;Australie : recrudescence des incendies, des milliers de touristes pourraient être pris au piège.\n.\n                                        Des centaines de feux de forêts brûlent actuellement à travers le continent, notamment dans la région très touristique d&#39;East Gippsland où des milliers de vacanciers pourraient être pris au piège en raison d&#39;une nouvelle vague de chaleur.                    Des milliers de touristes pourraient se retrouver lundi pris au piège dans le... Lire la suite&quot;       
## [2] &quot;Population : 5 956 978 habitants, la Nouvelle-Aquitaine est la 4e région la plus peuplée de France.\n.\n                                        Selon les derniers chiffres du recensement, 66 524 000 habitants vivent en France au 1er janvier 2017 dont 5 956 978 en Nouvelle-Aquitaine. Une région qui reste attractive et qui doit surtout sa hausse de population aux migrations résidentielles. .                    Au 1er janvier 2017, selon les chiffres publiés ce lundi 30 décembre par... Lire la suite&quot;</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="data-collect.html#cb22-1"></a><span class="co"># Create Quanteda corpus</span></span>
<span id="cb22-2"><a href="data-collect.html#cb22-2"></a>qd&lt;-<span class="kw">corpus</span>(df<span class="op">$</span>text)</span>
<span id="cb22-3"><a href="data-collect.html#cb22-3"></a></span>
<span id="cb22-4"><a href="data-collect.html#cb22-4"></a><span class="co"># Add date</span></span>
<span id="cb22-5"><a href="data-collect.html#cb22-5"></a>qd<span class="op">$</span>date&lt;-<span class="kw">as.POSIXct</span>(<span class="kw">strptime</span>(df<span class="op">$</span>publish_date,<span class="st">&quot;%Y-%m-%d %H:%M:%S&quot;</span>))</span>
<span id="cb22-6"><a href="data-collect.html#cb22-6"></a></span>
<span id="cb22-7"><a href="data-collect.html#cb22-7"></a><span class="co"># Add initial meta</span></span>
<span id="cb22-8"><a href="data-collect.html#cb22-8"></a><span class="kw">meta</span>(qd,<span class="st">&quot;language&quot;</span>)&lt;-df<span class="op">$</span>language[<span class="dv">1</span>]</span>
<span id="cb22-9"><a href="data-collect.html#cb22-9"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_id&quot;</span>)&lt;-df<span class="op">$</span>media_id[<span class="dv">1</span>]</span>
<span id="cb22-10"><a href="data-collect.html#cb22-10"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_name&quot;</span>)&lt;-df<span class="op">$</span>media_name[<span class="dv">1</span>]</span>
<span id="cb22-11"><a href="data-collect.html#cb22-11"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_url&quot;</span>)&lt;-df<span class="op">$</span>media_url[<span class="dv">1</span>]</span>
<span id="cb22-12"><a href="data-collect.html#cb22-12"></a></span>
<span id="cb22-13"><a href="data-collect.html#cb22-13"></a><span class="co"># Add supplementary meta</span></span>
<span id="cb22-14"><a href="data-collect.html#cb22-14"></a><span class="kw">meta</span>(qd,<span class="st">&quot;media_country&quot;</span>)&lt;-<span class="st">&quot;FRA&quot;</span></span>
<span id="cb22-15"><a href="data-collect.html#cb22-15"></a><span class="kw">meta</span>(qd,<span class="st">&quot;data_source&quot;</span>)&lt;-<span class="st">&quot;Media Cloud &quot;</span></span>
<span id="cb22-16"><a href="data-collect.html#cb22-16"></a><span class="kw">meta</span>(qd,<span class="st">&quot;data_time&quot;</span>)&lt;-<span class="st">&quot;Special extraction&quot;</span></span>
<span id="cb22-17"><a href="data-collect.html#cb22-17"></a><span class="kw">meta</span>(qd,<span class="st">&quot;data_author&quot;</span>)&lt;-<span class="st">&quot;Elaborated by Claude Grasland&quot;</span></span>
<span id="cb22-18"><a href="data-collect.html#cb22-18"></a></span>
<span id="cb22-19"><a href="data-collect.html#cb22-19"></a><span class="co"># Save in Rdata format</span></span>
<span id="cb22-20"><a href="data-collect.html#cb22-20"></a><span class="kw">saveRDS</span>(qd,<span class="dt">file =</span> <span class="kw">paste</span>(base, <span class="st">&quot;/qd/stories_&quot;</span>,id,<span class="st">&quot;.Rdata&quot;</span>, <span class="dt">sep=</span><span class="st">&quot;&quot;</span>))</span></code></pre></div>
</div>
</div>
<div id="data-level-3-full-text" class="section level2">
<h2><span class="header-section-number">3.3</span> DATA LEVEL 3 : Full text</h2>
<p>We consider finally the case of news based on full text. It is generally related to the selection of a precise corpus related to a specific topic (e.g. migration, border, …) in order to limit the size of the resulting database.</p>
<p>We can take the example of …</p>
<p><em>To be done.</em></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-check.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ClaudeGrasland/newsbook/edit/master/02-data-collection.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["newsbook.pdf", "newsbook.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
